# Generated by Django 5.1.1 on 2024-11-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsfeed",
            name="post_description",
            field=models.TextField(default=""),
        ),
    ]
