# Generated by Django 5.1.1 on 2024-11-21 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0002_alter_newsfeed_post_description"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsfeed",
            name="id",
        ),
        migrations.AddField(
            model_name="newsfeed",
            name="feed_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newsfeed",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_posts",
                to="users.user",
            ),
        ),
    ]
