# Generated by Django 5.1.1 on 2024-12-08 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0003_remove_newsfeed_id_newsfeed_feed_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsfeed",
            name="like_count",
        ),
        migrations.AddField(
            model_name="newsfeed",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
