# Generated by Django 5.1.1 on 2024-12-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0004_remove_newsfeed_like_count_newsfeed_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsfeed",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
