# Generated by Django 5.1.1 on 2024-12-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarevent",
            options={"ordering": ["-date", "-time"]},
        ),
    ]
