# Generated by Django 5.1.1 on 2024-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0002_alter_calendarevent_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
