# Generated by Django 5.1.1 on 2024-12-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_message_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_unsent",
            field=models.BooleanField(default=False),
        ),
    ]
