# Generated by Django 5.1.1 on 2024-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reward_points",
            field=models.PositiveIntegerField(
                default=0, help_text="Reward points for completing this task/event"
            ),
        ),
    ]
