# Generated by Django 5.1.1 on 2024-11-07 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('middleinit', models.CharField(blank=True, max_length=1, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('employmentStatus', models.CharField(max_length=100)),
            ],
        ),
    ]
