# Generated by Django 5.1.3 on 2024-12-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_status',
            field=models.CharField(choices=[('Active', 'Very Active'), ('Moderate', 'Moderately Active'), ('Low', 'Less Active'), ('Inactive', 'Inactive')], default='Active', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
