# Generated by Django 5.1.3 on 2024-12-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_activity_status_user_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
