# Generated by Django 5.1.4 on 2024-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_goals_user_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='middleinit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.AddField(
            model_name='user',
            name='banner_picture',
            field=models.ImageField(default='default_banner.jpg', upload_to='banner_pics'),
        ),
    ]
