# Generated by Django 5.1.3 on 2024-12-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_middleinit_remove_user_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banner_picture',
        ),
    ]
