# Generated by Django 5.1.1 on 2024-11-21 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("COMMUNITY_SERVICE", "Community Service"),
                            ("EDUCATION", "Education"),
                            ("ENVIRONMENT", "Environment"),
                            ("HEALTHCARE", "Healthcare"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        default=uuid.UUID("00000000-0000-0000-0000-000000000000"),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
