# Generated by Django 5.1.1 on 2024-11-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskManager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
    ]
