# Generated by Django 5.1.1 on 2024-11-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResourceHub",
            fields=[
                ("resource_id", models.AutoField(primary_key=True, serialize=False)),
                ("resource_title", models.CharField(max_length=255)),
                ("resource_description", models.TextField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("resource_category", models.CharField(max_length=100)),
                ("heart_count", models.IntegerField(default=0)),
                ("created_by", models.CharField(default="Anonymous", max_length=255)),
            ],
        ),
    ]
