# Generated by Django 5.1.1 on 2024-11-21 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resourcehub", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcehub",
            name="resource_category",
        ),
        migrations.AlterField(
            model_name="resourcehub",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resourcehub",
            name="resource_title",
            field=models.CharField(max_length=200),
        ),
    ]
