# Generated by Django 5.1.1 on 2024-12-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resourcehub", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resourcehub",
            old_name="heart_count",
            new_name="download_count",
        ),
    ]
