# Generated by Django 5.1.1 on 2024-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resourcehub", "0002_rename_heart_count_resourcehub_download_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcehub",
            name="resource_description",
            field=models.TextField(help_text="HTML content allowed"),
        ),
    ]
