# Generated by Django 5.1.1 on 2024-12-09 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resourcehub", "0003_alter_resourcehub_resource_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcehub",
            name="upload_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
