# Generated by Django 5.1.1 on 2024-11-21 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resourcehub", "0003_alter_resourcehub_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcehub",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
